In [1]:
import pandas as pd
import chardet
import os

In [2]:
data_customers_df = pd.read_csv('olist_customers_dataset.csv')
data_geolocation_df = pd.read_csv('olist_geolocation_dataset.csv')
data_order_items_df = pd.read_csv('olist_order_items_dataset.csv')
data_order_payments_df = pd.read_csv('olist_order_payments_dataset.csv')
data_order_reviews_df = pd.read_csv('olist_order_reviews_dataset.csv')
data_orders_df = pd.read_csv('olist_orders_dataset.csv')
data_products_df = pd.read_csv('olist_products_dataset.csv')
data_sellers_df = pd.read_csv('olist_sellers_dataset.csv')
data_category_name_translation_df = pd.read_csv('product_category_name_translation.csv')

In [ ]:
class DataCleaning:
    def __init__(self, data):
        # Si 'data' es un string, lo tratamos como ruta de archivo
        if isinstance(data, str):
            self.ruta = data
            self.nombre = os.path.basename(data)
            self.df = None
        # Si 'data' es un DataFrame, lo asignamos directamente
        elif isinstance(data, pd.DataFrame):
            self.ruta = None
            self.nombre = "DataFrame_en_Memoria"
            self.df = data.copy() # Usamos .copy() para no modificar el original
        self.encoding = None

    def visualizar_muestra(self, n=5):
        """Muestra las primeras n filas del dataset"""
        if self.df is not None:
            print(f"\n👀 Muestra de {self.nombre}:")
            display(self.df.head(n))
        else:
            print("⚠️ No hay datos cargados para mostrar la muestra.")
        return self
    
    # === PUNTO 1: INSPECCIÓN INICIAL Y CARGA ===
    def validar_y_cargar(self):
        """Si ya tenemos el df cargado, solo retornamos self"""
        if self.df is not None:
            print(f"✅ [PUNTO 1] Datos ya cargados en memoria ({self.nombre}).")
            return self
        
        # Si no, procedemos con la lógica original de carga de archivos
        if not os.path.exists(self.ruta):
            print(f"❌ Error: El archivo {self.nombre} no existe.")
            return self
            
        with open(self.ruta, 'rb') as f:
            resultado = chardet.detect(f.read(25000))
        
        self.encoding = resultado['encoding']
        self.df = pd.read_csv(self.ruta, encoding=self.encoding)
        print(f"✅ [PUNTO 1] {self.nombre} cargado con éxito. Encoding: {self.encoding.upper()}")
        return self
    
    def revisar_dimensiones(self):
        """Muestra el tamaño actual del dataset"""
        if self.df is not None:
            filas, columnas = self.df.shape
            print(f"📊 [PUNTO 1] Dimensiones: {filas} filas y {columnas} columnas.")
        else:
            print("⚠️ No hay datos cargados aún.")
        return self
    
    def revisar_tipos_datos(self):
        """
        [PUNTO 1] Muestra un resumen de los tipos de datos actuales 
        y detecta posibles columnas candidatas a corregir.
        """
        if self.df is None:
            print("⚠️ No hay datos cargados para revisar los tipos.")
            return self
            
        print(f"\n📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: {self.nombre}")
        print("-" * 60)
        
        # Recorremos cada columna para dar un reporte detallado
        for col in self.df.columns:
            tipo = self.df[col].dtype
            nulos = self.df[col].isnull().sum()
            porcentaje_nulos = (nulos / len(self.df)) * 100
            
            # Formateo visual limpio
            print(f"🔹 Columna: {col:<30} | Tipo: {str(tipo):<10} | Nulos: {nulos} ({porcentaje_nulos:.1f}%)")
            
        print("-" * 60)
        return self
    
    def corregir_tipo_datos(self):
        """
        Detecta y convierte tipos automáticamente: 
        1. Fechas (analizando el formato)
        2. Numéricos (limpiando caracteres extraños)
        """
        for col in self.df.columns:
            if self.df[col].dtype == 'object':
                # 1. Intentar fecha
                date_attempt = pd.to_datetime(self.df[col], errors='coerce')
                if date_attempt.notnull().mean() > 0.7:
                    self.df[col] = date_attempt
                    continue
                
                # 2. Intentar numérico (Flotantes y Enteros)
                # Primero limpiamos: quitamos comas, espacios, y signos de moneda si existen
                cleaned_col = self.df[col].astype(str).str.replace(',', '').str.replace(' ', '')
                
                # Intentamos convertir
                num_attempt = pd.to_numeric(cleaned_col, errors='coerce')
                
                # Si el porcentaje de éxito es alto (> 70%)
                if num_attempt.notnull().mean() > 0.7:
                    self.df[col] = num_attempt

                # 3. Si llega aquí, es String puro -> Limpiar y Optimizar
                self.df[col] = self.df[col].astype(str).str.strip().fillna('N/A')
                
                # 4. Optimización de cardinalidad (solo si no es demasiado único)
                num_unique = self.df[col].nunique()
                if num_unique / len(self.df) < 0.5:
                    self.df[col] = self.df[col].astype('category')
        return self
    
    def estandarizar_columnas(self):
        """
        Limpia y estandariza los nombres de las columnas:
        1. Quita espacios al inicio/final.
        2. Convierte a minúsculas.
        3. Reemplaza espacios internos por guiones bajos (snake_case).
        """
        # 1. strip() para espacios invisibles
        # 2. str.lower() para minúsculas
        # 3. str.replace(' ', '_') para formato snake_case
        self.df.columns = (
            self.df.columns.str.strip()
            .str.lower()
            .str.replace(' ', '_')
            .str.replace('-', '_') # También reemplazamos guiones por si acaso
        )
        print("Columnas estandarizadas a formato snake_case.")
        return self

In [40]:
ordenes_cleaner = DataCleaning('olist_orders_dataset.csv')


df_orders_perfecto = (ordenes_cleaner
                      .validar_y_cargar()
                      .revisar_dimensiones()
                      .revisar_tipos_datos()
                      .corregir_tipo_datos()
                      .estandarizar_columnas()
                      .revisar_tipos_datos()
                      .visualizar_muestra()
                      )

✅ [PUNTO 1] olist_orders_dataset.csv cargado con éxito. Encoding: ASCII
📊 [PUNTO 1] Dimensiones: 99441 filas y 8 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: olist_orders_dataset.csv
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_id                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_status                   | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_purchase_timestamp       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_approved_at              | Tipo: object     | Nulos: 160 (0.2%)
🔹 Columna: order_delivered_carrier_date   | Tipo: object     | Nulos: 1783 (1.8%)
🔹 Columna: order_delivered_customer_date  | Tipo: object     | Nulos: 2965 (3.0%)
🔹 Columna: order_estimated_delivery_date  | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: olist_orders_dataset.csv
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_id                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_status                   | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: order_purchase_timestamp       | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
🔹 Columna: order_approved_at              | Tipo: datetime64[ns] | Nulos: 160 (0.2%)
🔹 Columna: order_delivered_carrier_date   | Tipo: datetime64[ns] | Nulos: 1783 (1.8%)
🔹 Columna: order_delivered_customer_date  | Tipo: datetime64[ns] | Nulos: 2965 (3.0%)
🔹 Columna: order_estimated_delivery_date  | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de olist_orders_dataset.csv:

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [44]:
ordenes_cleaner_df = DataCleaning(data_orders_df)
customer_cleaner_df = DataCleaning(data_customers_df)
geolocation_cleaner_df = DataCleaning(data_geolocation_df)
order_items_cleaner_df = DataCleaning(data_order_items_df)
order_payments_cleaner_df = DataCleaning(data_order_payments_df)
order_reviews_cleaner_df = DataCleaning(data_order_reviews_df)
products_cleaner_df = DataCleaning(data_products_df)
sellers_cleaner_df = DataCleaning(data_sellers_df)
category_name_translation_cleaner_df = DataCleaning(data_category_name_translation_df)


df_orders_perfecto = (ordenes_cleaner_df
                      .validar_y_cargar()
                      .revisar_dimensiones()
                      .revisar_tipos_datos()
                      .corregir_tipo_datos()
                      .estandarizar_columnas()
                      .revisar_tipos_datos()
                      .visualizar_muestra()
                      )

df_customers_perfecto = (customer_cleaner_df
                         .validar_y_cargar()
                         .revisar_dimensiones()
                         .revisar_tipos_datos()
                         .corregir_tipo_datos()
                         .estandarizar_columnas()
                         .revisar_tipos_datos()
                         .visualizar_muestra()
                         )

df_geolocation_perfecto = (geolocation_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

df_order_items_perfecto = (order_items_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

df_order_payments_perfecto = (order_payments_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

df_order_reviews_perfecto = (order_reviews_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

df_products_perfecto = (products_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

df_sellers_perfecto = (sellers_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

df_category_name_translation_perfecto = (category_name_translation_cleaner_df
                            .validar_y_cargar()
                            .revisar_dimensiones()
                            .revisar_tipos_datos()
                            .corregir_tipo_datos()
                            .estandarizar_columnas()
                            .revisar_tipos_datos()
                            .visualizar_muestra()
                            )

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 99441 filas y 8 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_id                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_status                   | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_purchase_timestamp       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_approved_at              | Tipo: object     | Nulos: 160 (0.2%)
🔹 Columna: order_delivered_carrier_date   | Tipo: object     | Nulos: 1783 (1.8%)
🔹 Columna: order_delivered_customer_date  | Tipo: object     | Nulos: 2965 (3.0%)
🔹 Columna: order_estimated_delivery_date  | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_id                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_status                   | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: order_purchase_timestamp       | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
🔹 Columna: order_approved_at              | Tipo: datetime64[ns] | Nulos: 160 (0.2%)
🔹 Columna: order_delivered_carrier_date   | Tipo: datetime64[ns] | Nulos: 1783 (1.8%)
🔹 Columna: order_delivered_customer_date  | Tipo: datetime64[ns] | Nulos: 2965 (3.0%)
🔹 Columna: order_estimated_delivery_date  | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 99441 filas y 5 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: customer_id                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_unique_id             | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_zip_code_prefix       | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: customer_city                  | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_state                 | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: customer_id                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_unique_id             | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: customer_zip_code_prefix       | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: customer_city                  | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: customer_state                 | Tipo: category   | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 1000163 filas y 5 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: geolocation_zip_code_prefix    | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: geolocation_lat                | Tipo: float64    | Nulos: 0 (0.0%)
🔹 Columna: geolocation_lng                | Tipo: float64    | Nulos: 0 (0.0%)
🔹 Columna: geolocation_city               | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: geolocation_state              | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: geolocation_zip_code_prefix    | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: geolocation_lat                | Tipo: float64    | Nulos: 0 (0.0%)
🔹 Columna: geolocation_lng                | Tipo: float64    | Nulos: 0 (0.0%)
🔹 Columna: geolocation_city               | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: geolocation_state              | Tipo: category   | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 112650 filas y 7 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_item_id                  | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: product_id                     | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: seller_id                      | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: shipping_limit_date            | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: price                          | Tipo: float64    | Nulos: 0 (0.0%)
🔹 Columna: freight_value                  | Tipo: float64    | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_item_id                  | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: product_id                     | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: seller_id                      | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: shipping_limit_date            | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
🔹 Columna: price                          | Tipo: float64    | Nulos: 0 (0.0%)
🔹 Columna: freight_value                  | Tipo: float64    | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 103886 filas y 5 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: payment_sequential             | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: payment_type                   | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: payment_installments           | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: payment_value                  | Tipo: float64    | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: payment_sequential             | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: payment_type                   | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: payment_installments           | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: payment_value                  | Tipo: float64    | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 99224 filas y 7 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: review_id                      | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: review_score                   | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: review_comment_title           | Tipo: object     | Nulos: 87656 (88.3%)
🔹 Columna: review_comment_message         | Tipo: object     | Nulos: 58247 (58.7%)
🔹 Columna: review_creation_date           | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: review_answer_timestamp        | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: review_id                      | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: order_id                       | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: review_score                   | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: review_comment_title           | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: review_comment_message         | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: review_creation_date           | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
🔹 Columna: review_answer_timestamp        | Tipo: datetime64[ns] | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,nan,nan,2018-01-18,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,nan,nan,2018-03-10,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,nan,nan,2018-02-17,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,nan,Recebi bem antes do prazo estipulado.,2017-04-21,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,nan,Parabéns lojas lannister adorei comprar pela I...,2018-03-01,2018-03-02 10:26:53

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 32951 filas y 9 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: product_id                     | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: product_category_name          | Tipo: object     | Nulos: 610 (1.9%)
🔹 Columna: product_name_lenght            | Tipo: float64    | Nulos: 610 (1.9%)
🔹 Columna: product_description_lenght     | Tipo: float64    | Nulos: 610 (1.9%)
🔹 Columna: product_photos_qty             | Tipo: float64    | Nulos: 610 (1.9%)
🔹 Columna: product_weight_g               | Tipo: float64    | Nulos: 2 (0.0%)
🔹 Columna: product_length_cm              | Tipo: float64    | Nulos: 2 (0.0%)
🔹 Columna: product_height_cm              | Tipo: float64    | Nulos: 2 (0.0%)
🔹 Columna: product_width_cm               | Tipo: float64    | Nulos: 2 (0.0%)
------------------------------------------------------------

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: product_id                     | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: product_category_name          | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: product_name_lenght            | Tipo: float64    | Nulos: 610 (1.9%)
🔹 Columna: product_description_lenght     | Tipo: float64    | Nulos: 610 (1.9%)
🔹 Columna: product_photos_qty             | Tipo: float64    | Nulos: 610 (1.9%)
🔹 Columna: product_weight_g               | Tipo: float64    | Nulos: 2 (0.0%)
🔹 Columna: product_length_cm              | Tipo: float64    | Nulos: 2 (0.0%)
🔹 Columna: product_height_cm              | Tipo: float64    | Nulos: 2 (0.0%)
🔹 Columna: product_width_cm               | Tipo: float64    | Nulos: 2 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 3095 filas y 4 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: seller_id                      | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: seller_zip_code_prefix         | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: seller_city                    | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: seller_state                   | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------
Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: seller_id                      | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: seller_zip_code_prefix         | Tipo: int64      | Nulos: 0 (0.0%)
🔹 Columna: seller_city                    | Tipo: category   | Nulos: 0 (0.0%)
🔹 Columna: seller_state                   | Tipo: category   | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

✅ [PUNTO 1] Datos ya cargados en memoria (DataFrame_en_Memoria).
📊 [PUNTO 1] Dimensiones: 71 filas y 2 columnas.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: product_category_name          | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: product_category_name_english  | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------
Columnas estandarizadas a formato snake_case.

📋 [PUNTO 1] Diagnóstico de Tipos de Datos para: DataFrame_en_Memoria
------------------------------------------------------------
🔹 Columna: product_category_name          | Tipo: object     | Nulos: 0 (0.0%)
🔹 Columna: product_category_name_english  | Tipo: object     | Nulos: 0 (0.0%)
------------------------------------------------------------

👀 Muestra de DataFrame_en_Memoria:

C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');
C:\Users\Sebastian\AppData\Local\Temp\ipykernel_16200\2570439853.py:86: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  date_attempt = pd.to_datetime(self.df[col], errors='coerce');

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [46]:
df_final_orders_df = df_orders_perfecto.df
df_final_orders_df.info()

df_final_customers_df = df_customers_perfecto.df
df_final_customers_df.info()

df_final_geolocation_df = df_geolocation_perfecto.df
df_final_geolocation_df.info()

df_final_order_items_df = df_order_items_perfecto.df
df_final_order_items_df.info()

df_final_order_payments_df = df_order_payments_perfecto.df
df_final_order_payments_df.info()

df_final_order_reviews_df = df_order_reviews_perfecto.df
df_final_order_reviews_df.info()

df_final_products_df = df_products_perfecto.df
df_final_products_df.info()

df_final_sellers_df = df_sellers_perfecto.df
df_final_sellers_df.info()

df_final_category_name_translation_df = df_category_name_translation_perfecto.df
df_final_category_name_translation_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  category
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: category(1), datetime64[ns](5), object(2)
memory usage: 5.4+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 5 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   customer_id               99441 non-null  object
 1   customer_unique_id        99441 non-null  object
 2   customer_zip_code_prefix  99441 non-null  int64
 3   customer_city             99441 non-null  category
 4   customer_state            99441 non-null  category
dtypes: category(2), int64(1), object(2)
memory usage: 2.7+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000163 entries, 0 to 1000162
Data columns (total 5 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   geolocation_zip_code_prefix  1000163 non-null  int64
 1   geolocation_lat              1000163 non-null  float64
 2   geolocation_lng              1000163 non-null  float64
 3   geolocation_city             1000163 non-null  category
 4   geolocation_state            1000163 non-null  category
dtypes: category(2), float64(2), int64(1)
memory usage: 26.1 MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   order_id             112650 non-null  object
 1   order_item_id        112650 non-null  int64
 2   product_id           112650 non-null  category
 3   seller_id            112650 non-null  category
 4   shipping_limit_date  112650 non-null  datetime64[ns]
 5   price                112650 non-null  float64
 6   freight_value        112650 non-null  float64
dtypes: category(2), datetime64[ns](1), float64(2), int64(1), object(1)
memory usage: 6.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103886 entries, 0 to 103885
Data columns (total 5 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   order_id              103886 non-null  object
 1   payment_sequential    103886 non-null  int64
 2   payment_type          103886 non-null  category
 3   payment_installments  103886 non-null  int64
 4   payment_value         103886 non-null  float64
dtypes: category(1), float64(1), int64(2), object(1)
memory usage: 3.3+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  object
 1   order_id                 99224 non-null  object
 2   review_score             99224 non-null  int64
 3   review_comment_title     99224 non-null  category
 4   review_comment_message   99224 non-null  category
 5   review_creation_date     99224 non-null  datetime64[ns]
 6   review_answer_timestamp  99224 non-null  datetime64[ns]
dtypes: category(2), datetime64[ns](2), int64(1), object(2)
memory usage: 5.8+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32951 entries, 0 to 32950
Data columns (total 9 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   product_id                  32951 non-null  object
 1   product_category_name       32951 non-null  category
 2   product_name_lenght         32341 non-null  float64
 3   product_description_lenght  32341 non-null  float64
 4   product_photos_qty          32341 non-null  float64
 5   product_weight_g            32949 non-null  float64
 6   product_length_cm           32949 non-null  float64
 7   product_height_cm           32949 non-null  float64
 8   product_width_cm            32949 non-null  float64
dtypes: category(1), float64(7), object(1)
memory usage: 2.0+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3095 entries, 0 to 3094
Data columns (total 4 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   seller_id               3095 non-null   object
 1   seller_zip_code_prefix  3095 non-null   int64
 2   seller_city             3095 non-null   category
 3   seller_state            3095 non-null   category
dtypes: category(2), int64(1), object(1)
memory usage: 79.2+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     object
 1   product_category_name_english  71 non-null     object
dtypes: object(2)
memory usage: 1.2+ KB

In [47]:
output_folder = 'data_limpia'
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"📁 Carpeta '{output_folder}' creada.")

# 2. Crear un diccionario con tus objetos ya procesados
# Esto mapea el nombre que quieres para el archivo con el objeto de tu clase
datasets = {
    'orders': df_orders_perfecto,
    'customers': df_customers_perfecto,
    'geolocation': df_geolocation_perfecto,
    'order_items': df_order_items_perfecto,
    'order_payments': df_order_payments_perfecto,
    'order_reviews': df_order_reviews_perfecto,
    'products': df_products_perfecto,
    'sellers': df_sellers_perfecto,
    'category_translation': df_category_name_translation_perfecto
}

# 3. Iterar y guardar
for name, obj in datasets.items():
    file_path = os.path.join(output_folder, f'{name}_limpio.csv')
    obj.df.to_csv(file_path, index=False)
    print(f"✅ Guardado: {file_path}")

📁 Carpeta 'data_limpia' creada.
✅ Guardado: data_limpia\orders_limpio.csv
✅ Guardado: data_limpia\customers_limpio.csv
✅ Guardado: data_limpia\geolocation_limpio.csv
✅ Guardado: data_limpia\order_items_limpio.csv
✅ Guardado: data_limpia\order_payments_limpio.csv
✅ Guardado: data_limpia\order_reviews_limpio.csv
✅ Guardado: data_limpia\products_limpio.csv
✅ Guardado: data_limpia\sellers_limpio.csv
✅ Guardado: data_limpia\category_translation_limpio.csv